import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, useContext, useEffect, useState } from 'react';

export type LanguageCode = 'es' | 'en';

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => Promise<void>;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Direct key mapping for English translations (where keys are the exact Spanish strings)
const enTranslations: Record<string, string> = {
  // --- UI GENERAL & PROFILE ---
  "Mi Cuenta Laika Club": "My Laika Club Account",
  "Ajustes de Perfil": "Profile Settings",
  "Ajustes": "Settings",
  "Historial": "History",
  "Descubrir": "Discover",
  "Beneficios": "Benefits",
  "PROGRAMA DE FIDELIDAD LAIKA CLUB": "LAIKA CLUB LOYALTY PROGRAM",
  "Socio Nivel Bronce": "Bronze Level Member",
  "Socio Nivel Plata": "Silver Level Member",
  "Socio Nivel Oro": "Gold Level Member",
  "Socio Nivel": "Member Level",
  "Socio": "Member",
  "Shows": "Shows",
  "Progreso al nivel": "Progress to level",
  "Ajustes de Perfil ": "Profile Settings ",
  "Editar Perfil": "Edit Profile",
  "Nombre de usuario": "Username",
  "Correo electrónico": "Email Address",
  "Rol en el sistema": "System Role",
  "Preferencia de Tema": "Theme Preference",
  "Modo de visualización": "Display Mode",
  "Oscuro (Monocromático)": "Dark (Monochromatic)",
  "Claro (Monocromático)": "Light (Monochromatic)",
  "Métodos de Pago Guardados": "Saved Payment Methods",
  "No tienes tarjetas guardadas": "You have no saved cards",
  "Para guardar una tarjeta haz una compra de boletos o registra una tarjeta de pruebas aquí.": "To save a card, make a ticket purchase or register a test card here.",
  "Vincular Tarjeta Demo": "Link Demo Card",
  "Visa •••• ": "Visa •••• ",
  "TITULAR": "HOLDER",
  "VENCE": "EXPIRY",
  "Eliminar Tarjeta": "Delete Card",
  "¿Deseas desvincular tu tarjeta del perfil?": "Do you want to unlink your card from the profile?",
  "Eliminar": "Delete",
  "Tarjeta Eliminada": "Card Deleted",
  "Tus métodos de pago han sido borrados de tu perfil.": "Your payment methods have been cleared from your profile.",
  "Tarjeta Registrada": "Card Registered",
  "Se ha guardado una tarjeta de pruebas exitosamente.": "A test card has been saved successfully.",
  "Géneros Musicales Preferidos": "Preferred Music Genres",
  "Selecciona tus géneros favoritos para que podamos recomendarte eventos alineados a tus gustos.": "Select your favorite genres so we can recommend events tailored to your tastes.",
  "Cerrar Sesión": "Log Out",
  "¿Estás seguro de que deseas salir de tu cuenta?": "Are you sure you want to log out of your account?",
  "¿Estás seguro de que deseas salir de la cuenta de Operador?": "Are you sure you want to log out of the Operator account?",
  "Cancelar": "Cancel",
  "Guardar": "Save",
  "Cargando perfil...": "Loading profile...",
  "Inicia sesión o regístrate para poder comprar boletos, recibir reembolsos, registrar tus pases y acceder a tu Wallet digital.": "Log in or register to purchase tickets, receive refunds, register your passes, and access your digital Wallet.",
  "Iniciar Sesión / Registrarse": "Log In / Register",
  "Asiste a 3 eventos para subir a Socio Plata y recibir preventas anticipadas!": "Attend 3 events to level up to Silver Member and receive early presales!",
  "Asiste a 6 eventos para ser Socio Oro, obtener 10% de descuento en el Bazar y fila rápida!": "Attend 6 events to become a Gold Member, get 10% off at the Bazaar and fast track queueing!",
  "¡Felicidades! Tienes preventas exclusivas, 10% de descuento en Bazaar y acceso VIP.": "Congratulations! You have exclusive presales, 10% off at the Bazaar, and VIP access.",

  // --- EDIT PROFILE MODAL ---
  "Editar Datos Personales": "Edit Personal Data",
  "Seleccionar Foto de Perfil": "Select Profile Picture",
  "URL de Foto Personalizada (Opcional)": "Custom Photo URL (Optional)",
  "Nombre Completo": "Full Name",
  "Correo Electrónico": "Email Address",
  "Cambiar Contraseña (Opcional)": "Change Password (Optional)",
  "Nueva Contraseña": "New Password",
  "Confirmar Contraseña": "Confirm Password",
  "El nombre es requerido": "Name is required",
  "El correo es requerido": "Email is required",
  "El formato del correo es inválido": "Email format is invalid",
  "La contraseña debe tener al menos 6 caracteres": "Password must be at least 6 characters long",
  "Las contraseñas no coinciden": "Passwords do not match",
  "Perfil Actualizado": "Profile Updated",
  "Tus datos de cuenta y credenciales han sido actualizados con éxito.": "Your account data and credentials have been updated successfully.",
  "No se pudo guardar la información del perfil.": "Could not save profile information.",
  "Ingresa tu nombre completo": "Enter your full name",
  "Ingresa tu correo electrónico": "Enter your email address",
  "Repite la nueva contraseña": "Repeat the new password",
  "Mínimo 6 caracteres": "Minimum 6 characters",
  "Error": "Error",

  // --- EVENTS & CHECKOUT ---
  "Explora Espectáculos": "Explore Shows",
  "Laika Club Arena & Foro Monumental": "Laika Club Arena & Monumental Forum",
  "Buscar conciertos, complejos...": "Search concerts, venues...",
  "No se encontraron eventos disponibles": "No available events were found",
  "Desde": "Starting at",
  "Reservar Lugar": "Book Seat",
  "Volver a Detalles": "Back to Details",
  "ESCENARIO": "STAGE",
  "VIP": "VIP",
  "Gold": "Gold",
  "Gral": "General",
  "Mi Selección": "My Selection",
  "Ocupado": "Occupied",
  "Boletos Seleccionados": "Selected Tickets",
  "Total Estimado:": "Estimated Total:",
  "Agregar al Carrito": "Add to Cart",
  "Comprar Ahora": "Buy Now",
  "Resumen de Orden": "Order Summary",
  "Monto a Pagar:": "Amount to Pay:",
  "Bypass Gateway LaikaPay": "Bypass Gateway LaikaPay",
  "Confirmación instantánea de balance": "Instant balance confirmation",
  "Atrás": "Back",
  "Confirmar y Pagar": "Confirm & Pay",
  "¡Compra Exitosa!": "Purchase Successful!",
  "Tus boletos han sido generados y agregados a tu Wallet digital. Puedes presentarlos sin conexión en la puerta de acceso del recinto.": "Your tickets have been generated and added to your digital Wallet. You can present them offline at the venue gate.",
  "Listo, Volver al Inicio": "Done, Back to Home",
  "Completar Pago Seguro": "Complete Secure Payment",
  "Carrito de Compra": "Shopping Cart",
  "Ingresa los detalles de tu pago": "Enter your payment details",
  "boletos seleccionados": "selected tickets",
  "Tu carrito está vacío": "Your cart is empty",
  "Agrega asientos de cualquier evento para iniciar.": "Add seats from any event to start.",
  "Explorar Eventos": "Explore Events",
  "Asientos Seleccionados:": "Selected Seats:",
  "Souvenirs Vinculados:": "Linked Souvenirs:",
  "Subtotal Evento:": "Event Subtotal:",
  "Total del Carrito:": "Cart Total:",
  "Proceder al Pago": "Proceed to Payment",
  "Monto Final:": "Final Amount:",
  "Tarjeta": "Card",
  "PayPal": "PayPal",
  "OXXO Pay": "OXXO Pay",
  "Método de Pago Registrado": "Registered Payment Method",
  "Titular:": "Holder:",
  "Vence:": "Expiry:",
  "Cambiar": "Change",
  "Usar guardada": "Use saved",
  "Información de la Tarjeta": "Card Information",
  "Titular de la Tarjeta": "Cardholder Name",
  "Nombre completo impreso": "Full name printed on card",
  "Número de Tarjeta": "Card Number",
  "Expiración": "Expiration",
  "Conexión Encriptada SSL. Cumple con norma PCI-DSS.": "SSL Encrypted Connection. PCI-DSS compliant.",
  "Autenticación Directa PayPal": "PayPal Direct Authentication",
  "Al presionar pagar, se abrirá un portal seguro de PayPal para autorizar tu saldo o saldo en cuenta bancaria asociada.": "By pressing pay, a secure PayPal portal will open to authorize your balance or associated bank account.",
  "Pay Later & Protección al Comprador Activa.": "Pay Later & Buyer Protection Active.",
  "Ficha de Pago OXXO Pay": "OXXO Pay Slip",
  "Se generará un código de barras único para pagar en efectivo en cualquier tienda OXXO de la República. El saldo se acredita en 5 minutos.": "A unique barcode will be generated to pay in cash at any OXXO store. Balance is credited in 5 minutes.",
  "Comisión de $15 MXN cobrada en ventanilla.": "$15 MXN fee charged at counter.",
  "Procesando...": "Processing...",
  "Todos tus boletos han sido generados con éxito y agregados a tu Wallet digital. Puedes presentarlos sin conexión en la puerta de acceso.": "All your tickets have been generated successfully and added to your digital Wallet. You can present them offline at the access gate.",
  "Entendido, Ir a Eventos": "Understood, Go to Events",
  "Límite excedido": "Limit exceeded",
  "Solo puedes comprar un máximo de 6 boletos por transacción.": "You can only purchase a maximum of 6 tickets per transaction.",
  "Sin selección": "No selection",
  "Por favor, selecciona al menos un asiento.": "Please select at least one seat.",
  "Error de red": "Network error",
  "La compra no pudo ser transmitida al servidor.": "The purchase could not be transmitted to the server.",
  "Selección vacía": "Empty selection",
  "Por favor selecciona al menos un asiento.": "Please select at least one seat.",
  "Carrito actualizado": "Cart updated",
  "Los asientos y souvenirs han sido agregados a tu carrito.": "Seats and souvenirs have been added to your cart.",
  "Agregado al carrito": "Added to cart",
  "El concierto, asientos y souvenirs han sido agregados a tu carrito.": "The concert, seats, and souvenirs have been added to your cart.",
  "Solo puedes comprar un máximo de 6 boletos por evento.": "You can only purchase a maximum of 6 tickets per event.",
  "Datos incompletos": "Incomplete data",
  "Por favor ingresa el nombre del titular.": "Please enter the cardholder's name.",
  "Número incorrecto": "Incorrect number",
  "Por favor ingresa un número de tarjeta válido.": "Please enter a valid card number.",
  "Vencimiento incorrecto": "Incorrect expiration",
  "Por favor ingresa la fecha de expiración MM/AA.": "Please enter expiration date MM/YY.",
  "CVV incorrecto": "Incorrect CVV",
  "Por favor ingresa un código de seguridad válido.": "Please enter a valid security code.",
  "Hubo un inconveniente al procesar la compra.": "There was an issue processing your purchase.",
  "Cargando catálogo de eventos...": "Loading events catalog...",
  "Descripción del Evento": "Event Description",
  "Información Relevante": "Relevant Information",
  "Productos Oficiales del Evento": "Official Event Merchandise",
  "Agregar": "Add",
  "Seguridad:": "Security:",
  "Bolsos sujetos a revisión. Prohibido ingresar cámaras profesionales, objetos punzocortantes, alimentos y bebidas.": "Bags subject to search. Professional cameras, sharp objects, food, and drinks are prohibited.",
  "Acceso digital:": "Digital access:",
  "Presenta tu boleto QR digital desde la Wallet. No requiere conexión a internet en la entrada.": "Present your digital QR ticket from the Wallet. Does not require internet connection at the entrance.",
  "Horarios:": "Schedules:",
  "Las puertas abren 1.5 horas antes del espectáculo. Se recomienda llegar temprano.": "Doors open 1.5 hours before the show. Early arrival is recommended.",

  // --- TABS & NAVIGATION ---
  "Boletos": "Tickets",
  "Bazar": "Bazaar",
  "Calificar Eventos": "Rate Events",
  "VIGENTE": "ACTIVE",
  "CANJEADO": "REDEEMED",
  "REEMBOLSADO": "REFUNDED",
  "FECHA Y HORA": "DATE & TIME",
  "ASIENTO": "SEAT",
  "SOUVENIRS ADQUIRIDOS": "PURCHASED SOUVENIRS",
  "Ver Código QR Acceso": "View Access QR Code",
  "No has comprado boletos aún.": "You haven't bought tickets yet.",
  "Código:": "Code:",
  "Fecha:": "Date:",
  "ENTREGADO": "DELIVERED",
  "PREPARANDO": "PREPARING",
  "TOTAL DE COMPRA": "ORDER TOTAL",
  "No tienes pedidos del Bazar.": "You have no Bazaar orders.",
  "Únicamente las personas que compraron boletos para un concierto y ya asistieron pueden calificar y dejar su opinión pública.": "Only users who purchased tickets for a concert and already attended can rate and leave a public review.",
  "Seleccionar Evento Comprado": "Select Purchased Event",
  "No has comprado boletos para ningún evento": "You haven't bought tickets for any event",
  "Calificación del Evento": "Event Rating",
  "Comentario / Opinión": "Comment / Review",
  "Publicar Calificación": "Publish Rating",
  "Mis Opiniones Enviadas": "My Submitted Reviews",
  "No has enviado ninguna opinión aún.": "You haven't submitted any reviews yet.",
  "Opinión Registrada": "Review Registered",
  "¡Gracias por compartir tu reseña! Recibiste +40 XP.": "Thanks for sharing your review! You received +40 XP.",
  "Enviado el:": "Submitted on:",
  "Comparte tu experiencia acerca del show, audio del recinto, organización...": "Share your experience about the show, venue sound, organization...",

  // --- EXPLORE & RECOMMENDATIONS ---
  "Artistas que sigo": "Artists I follow",
  "¡De Gira!": "On Tour!",
  "Siguiendo": "Following",
  "Seguir": "Follow",
  "Recomendados para ti": "Recommended for you",
  "Selecciona más géneros musicales en tus Ajustes o sigue artistas para recibir recomendaciones personalizadas.": "Select more music genres in your Settings or follow artists to receive personalized recommendations.",
  "DESDE": "FROM",

  // --- BENEFITS & COUPONS ---
  "Mis Cupones de Descuento": "My Discount Coupons",
  "No tienes cupones de descuento disponibles.": "You have no discount coupons available.",
  "Expira:": "Expires:",
  "Ofertas Relámpago y Promociones": "Flash Deals & Promotions",
  "OFERTA 2X1": "2X1 DEAL",
  "Expira en 4h": "Expires in 4h",
  "Doble Diversión en Electrónica": "Double Fun in Electronic",
  "Compra 1 boleto para Steve Aoki - Neon Party en zona general y recibe el segundo completamente gratis. ¡Promoción por tiempo limitado!": "Buy 1 ticket for Steve Aoki - Neon Party in general area and receive the second one completely free. Limited time promotion!",
  "Aprovechar 2x1": "Claim 2x1 Deal",
  "Bandeja de Notificaciones": "Notifications Inbox",
  "Boleto Digital Acceso": "Digital Access Ticket",
  "Presenta este código en el escáner del recinto. Se recomienda brillo de pantalla al máximo.": "Present this code at the venue scanner. Maximum screen brightness is recommended.",

  // --- BAZAR / SOUVENIRS ---
  "Bazar de Souvenirs": "Souvenirs Bazaar",
  "Mercancía Oficial Coldplay, Duki & Aoki": "Official Coldplay, Duki & Aoki Merchandise",
  "Entrar": "Login",
  "Filtrado por eventos en carrito": "Filtered by events in cart",
  "Mostrar Todo": "Show All",
  "Mi Carrito de Compras": "My Shopping Cart",
  "El carrito está vacío": "The cart is empty",
  "Total Compra:": "Total Purchase:",
  "Limpiar": "Clear",
  "Completar Pedido": "Complete Order",
  "¡Pedido Registrado!": "Order Placed!",
  "Tu orden de souvenirs ha sido procesada con éxito. Puedes recoger tu mercancía en los stands del club en la entrada del evento mostrando tu nombre de usuario.": "Your souvenirs order has been successfully processed. You can collect your merchandise at the club stands at the event entrance by showing your username.",
  "Entendido, Volver al Bazar": "Understood, Back to Bazaar",
  "Inicio de Sesión Requerido": "Login Required",
  "Para realizar compras de mercancía es necesario estar registrado e iniciar sesión.": "To purchase merchandise, you must be registered and logged in.",
  "Cargando bazar de souvenirs...": "Loading souvenirs bazaar...",

  // --- OPERATOR ACCESS CONTROL ---
  "Control de Acceso": "Access Control",
  "Escaneo en puerta del recinto y registro de boletos.": "Venue gate scanning and ticket registration.",
  "Escaneados": "Scanned",
  "Válidos": "Valid",
  "Alertas": "Alerts",
  "Lector QR de Acceso": "Access QR Reader",
  "Cargando lector...": "Loading reader...",
  "El lector de cámara está inactivo": "The camera reader is inactive",
  "Habilitar Cámara": "Enable Camera",
  "Reactivar Lector": "Reactivate Reader",
  "Código de boleto (Ej: TKT-VALID)": "Ticket code (E.g. TKT-VALID)",
  "ACCESO PERMITIDO": "ACCESS GRANTED",
  "BOLETO YA REIVINDICADO": "TICKET ALREADY CLAIMED",
  "ACCESO DENEGADO": "ACCESS DENIED",
  "Error de Validación": "Validation Error",
  "Titular Actual:": "Current Holder:",
  "Comprador Original:": "Original Buyer:",
  "Espectáculo:": "Show:",
  "Recinto / Lugar:": "Venue / Location:",
  "Zona / Asiento:": "Zone / Seat:",
  "Fecha y Hora:": "Date & Time:",
  "Precio Pagado:": "Price Paid:",
  "Redimido el:": "Redeemed on:",
  "Registrar Incidencia": "Log Incident",
  "Reportar como Sospechoso": "Report as Suspicious",
  "Búsqueda Manual de Asistentes": "Manual Attendee Search",
  "Nombre, correo o código...": "Name, email or code...",
  "Buscando...": "Searching...",
  "Validar": "Validate",
  "Usado": "Used",
  "Devuelto": "Refunded",
  "Simulación de Escaneo (Desarrollo)": "Scan Simulation (Development)",
  "QR Válido": "Valid QR",
  "QR Usado": "Used QR",
  "QR Inválido": "Invalid QR",
  "Validando boleto...": "Validating ticket...",
  "Código Requerido": "Code Required",
  "Por favor, ingrese un código de boleto.": "Please enter a ticket code.",
  "No se pudo realizar la búsqueda de asistentes.": "Could not search attendees.",

  // --- CATEGORIES (DATA) ---
  "Urbano": "Urban",
  "Convención": "Convention",
  "Electrónica": "Electronic",
  "Rock": "Rock",
  "Pop": "Pop",
  "Indie": "Indie",

  // --- DYNAMIC DATA: EVENT TITLES & VENUES ---
  "Duki - A.D.A. Tour 2026": "Duki - A.D.A. Tour 2026",
  "Estadio Laika Arena": "Laika Arena Stadium",
  "Coldplay - Music of the Spheres Tour": "Coldplay - Music of the Spheres Tour",
  "Foro Sol Monumental": "Monumental Foro Sol",
  "Steve Aoki - Neon Party": "Steve Aoki - Neon Party",
  "Club Omnia Club": "Omnia Club",
  "Gamer Con 2026": "Gamer Con 2026",
  "Centro de Exposiciones Laika Center": "Laika Center Exhibition Center",
  "Bad Bunny - Most Wanted Tour": "Bad Bunny - Most Wanted Tour",
  "Estadio Azteca": "Azteca Stadium",
  "Taylor Swift - The Eras Tour": "Taylor Swift - The Eras Tour",
  "Metallica - M72 World Tour": "Metallica - M72 World Tour",
  "Arena Ciudad de México": "Mexico City Arena",
  "Martin Garrix - Live Beats": "Martin Garrix - Live Beats",
  "Explanada Laika Park": "Laika Park Esplanade",
  "Billie Eilish - Hit Me Hard and Soft": "Billie Eilish - Hit Me Hard and Soft",
  "Palacio de los Deportes": "Sports Palace",
  "Bruno Mars - Live in Concert": "Bruno Mars - Live in Concert",
  "Iron Maiden - Future Past Tour": "Iron Maiden - Future Past Tour",
  "Daft Punk Tribute - Laser Show": "Daft Punk Tribute - Laser Show",
  "Planetario Laika Dome": "Laika Dome Planetarium",
  "Karol G - Mañana Será Bonito": "Karol G - Mañana Será Bonito",
  "The Weeknd - After Hours til Dawn": "The Weeknd - After Hours til Dawn",
  "Red Hot Chili Peppers - Unlimited Love": "Red Hot Chili Peppers - Unlimited Love",
  "Tomorrowland Unite México": "Tomorrowland Unite Mexico",
  "Rock in Laika Festival": "Rock in Laika Festival",
  "Indie Fest 2026": "Indie Fest 2026",
  "Jardines de Laika Arena": "Laika Arena Gardens",
  "Anime & Manga Fest": "Anime & Manga Fest",
  "Travis Scott - Utopia Tour": "Travis Scott - Utopia Tour",
  "Eminem - The Resurrection Tour": "Eminem - The Resurrection Tour",
  "Shakira - Las Mujeres Ya No Lloran": "Shakira - Las Mujeres Ya No Lloran",
  "Peso Pluma - Éxodo Tour": "Peso Pluma - Éxodo Tour",
  "Bizarrap - Live Session": "Bizarrap - Live Session",
  "Justin Bieber - Justice Tour": "Justin Bieber - Justice Tour",

  // --- DYNAMIC DATA: EVENT DESCRIPTIONS ---
  "El referente mundial de la música urbana llega a México para presentar su nuevo álbum A.D.A. junto con sus mayores éxitos globales en una noche legendaria.": "The global reference of urban music arrives in Mexico to present his new album A.D.A. along with his greatest global hits in a legendary night.",
  "Disfruta de una experiencia inmersiva con luces LED, fuegos artificiales y una puesta en escena espectacular e inolvidable con conciencia ecológica.": "Enjoy an immersive experience with LED lights, fireworks, and a spectacular and unforgettable staging with ecological consciousness.",
  "El DJ y productor superestrella Steve Aoki llenará de beats electrónicos y lanzamientos de pasteles la pista en la mejor fiesta electrónica del año.": "Superstar DJ and producer Steve Aoki will fill the dancefloor with electronic beats and cake throwing in the best electronic party of the year.",
  "La convención anual de videojuegos y cosplay más importante del país. Zona de eSports, torneos retro, booths interactivos y conferencias de creadores.": "The country's most important annual video game and cosplay convention. eSports zone, retro tournaments, interactive booths, and creator conferences.",
  "El Conejo Malo regresa con un espectáculo sin precedentes dedicado a sus raíces trap y sus hits número uno a nivel mundial.": "The Bad Bunny returns with an unprecedented show dedicated to his trap roots and his number one hits worldwide.",
  "Un viaje a través de todas las eras musicales de la carrera de Taylor Swift, con una producción masiva e inolvidable.": "A journey through all the musical eras of Taylor Swift's career, with a massive and unforgettable production.",
  "La legendaria banda de metal regresa con su icónico escenario circular y un setlist doble en dos noches inolvidables.": "The legendary metal band returns with their iconic circular stage and a double setlist in two unforgettable nights.",
  "Disfruta de la magia electrónica de uno de los mejores DJs del mundo en una noche llena de luces, lásers y pirotecnia.": "Enjoy the electronic magic of one of the world's best DJs in a night filled with lights, lasers, and pyrotechnics.",
  "Presentando su nuevo material discográfico con un show íntimo pero espectacular que destaca su inigualable rango vocal y estilo alternativo.": "Presenting her new record material with an intimate but spectacular show highlighting her unique vocal range and alternative style.",
  "El rey del funk y el pop regresa con su espectacular banda The Hooligans para hacernos bailar con su inigualable energía.": "The king of funk and pop returns with his spectacular band The Hooligans to make us dance with his unique energy.",
  "Un show épico que celebra lo mejor de Somewhere in Time, Senjutsu y sus mayores clásicos con Eddie en escena.": "An epic show celebrating the best of Somewhere in Time, Senjutsu, and their greatest classics with Eddie on stage.",
  "Una experiencia sensorial de luces y lásers sincronizada con los mayores éxitos de Daft Punk en vivo.": "A sensory experience of lights and lasers synchronized with Daft Punk's greatest hits live.",
  "La Bichota llega con su vibra positiva, tiernos animales mágicos en el escenario y todos sus éxitos urbanos.": "La Bichota arrives with her positive vibe, cute magical animals on stage, and all her urban hits.",
  "Una noche teatral y cinematográfica que recorre el desierto de luces rojas y sintetizadores de The Weeknd.": "A theatrical and cinematic night that tours The Weeknd's desert of red lights and synthesizers.",
  "Los californianos regresan con John Frusciante en la guitarra en una sesión pura de funk rock y energía ilimitada.": "The Californians return with John Frusciante on guitar in a pure session of funk rock and unlimited energy.",
  "La conexión satelital en vivo con el festival de música electrónica más grande del mundo, con DJs en vivo locales e internacionales.": "The live satellite connection with the world's largest electronic music festival, with local and international live DJs.",
  "Un festival dedicado enteramente al rock en español y alternativo. 12 bandas nacionales en un solo día.": "A festival dedicated entirely to rock in Spanish and alternative. 12 national bands in a single day.",
  "Descubre los nuevos proyectos emergentes y consolidados del movimiento indie alternativo internacional.": "Discover the new emerging and established projects of the international alternative indie movement.",
  "La celebración de la cultura japonesa más grande del año. Cosplay, stands de venta oficiales, actores de doblaje y conciertos de anisong.": "The biggest celebration of Japanese culture of the year. Cosplay, official sales stands, voice actors, and anisong concerts.",
  "Una experiencia audiovisual inmersiva y de alta intensidad. Vive la utopía trap con Travis Scott en vivo.": "An immersive and high-intensity audiovisual experience. Live the trap utopia with Travis Scott live.",
  "El dios del rap Slim Shady regresa a los escenarios en un show que resume sus mayores batallas y éxitos clásicos.": "The rap god Slim Shady returns to the stages in a show that summarizes his greatest battles and classic hits.",
  "La estrella mundial del pop latino regresa con un despliegue de baile, hits históricos y una producción de vanguardia.": "The global Latin pop star returns with a display of dance, historical hits, and a cutting-edge production.",
  "La máxima estrella del regional mexicano y los corridos tumbados llega para una noche histórica de fiesta.": "The maximum star of Mexican regional and corridos tumbados arrives for a historic night of party.",
  "El productor estrella argentino Bizarrap presenta su aclamado espectáculo visual tocando sus sesiones más virales.": "The Argentine star producer Bizarrap presents his acclaimed visual show playing his most viral sessions.",
  "La superestrella del pop mundial regresa con su tour mundial Justice en una noche de hits coreados por miles.": "The global pop superstar returns with his Justice world tour in a night of hits cheered by thousands.",

  // --- DYNAMIC DATA: MERCHANDISE GOODS ---
  "Playera Oficial Duki A.D.A Tour": "Official Duki A.D.A Tour T-Shirt",
  "Algodón 100% premium, estampado de alta durabilidad en espalda y frente, edición limitada del tour.": "100% premium cotton, high durability print on back and front, limited tour edition.",
  "Gorra Laika Neon Black": "Laika Neon Black Cap",
  "Gorra ajustable tipo snapback con logo bordado en hilo neón de alta calidad.": "Adjustable snapback cap with logo embroidered in high quality neon thread.",
  "Lanyard Conmemorativa Laika VIP": "VIP Laika Commemorative Lanyard",
  "Ideal para colgar tu gafete o llaves, sublimación de doble vista con fibras recicladas.": "Ideal for hanging your badge or keys, double-sided sublimation with recycled fibers.",
  "Termo de Acero Inoxidable Coldplay": "Coldplay Stainless Steel Thermos",
  "Capacidad de 750ml, aislamiento de doble capa para mantener bebidas frías o calientes por 12 horas.": "750ml capacity, double-layer insulation to keep drinks cold or hot for 12 hours.",
  "Sudadera Bad Bunny \"Most Wanted\"": "Bad Bunny \"Most Wanted\" Hoodie",
  "Sudadera con gorro y bolsa frontal, diseño exclusivo del tour \"Most Wanted\" en serigrafía.": "Hoodie with front pocket, exclusive \"Most Wanted\" tour design in screen printing.",
  "Pulsera LED Coldplay Neon": "Coldplay Neon LED Wristband",
  "Pulsera interactiva con luz LED que parpadea al ritmo de los sensores de audio.": "Interactive bracelet with LED light that blinks to the rhythm of audio sensors.",
  "Playera Metallica M72 Tour": "Metallica M72 Tour T-Shirt",
  "Playera de manga corta con el imponente arte del tour mundial M72 de Metallica.": "Short sleeve t-shirt with Metallica's imposing M72 world tour art.",
  "Gorra Steve Aoki Cake": "Steve Aoki Cake Cap",
  "Gorra oficial con el divertido logo \"Cake Me\" del DJ Steve Aoki.": "Official cap with DJ Steve Aoki's fun \"Cake Me\" logo.",
  "Playera Taylor Swift The Eras Tour": "Taylor Swift The Eras Tour T-Shirt",
  "Playera oficial con el collage de fotos de las eras de Taylor Swift.": "Official t-shirt with Taylor Swift's eras photo collage.",
  "Tote Bag Billie Eilish Blohsh": "Billie Eilish Blohsh Tote Bag",
  "Bolsa ecológica de lona resistente con el icónico isotipo Blohsh de Billie Eilish.": "Eco-friendly resistant canvas bag with Billie Eilish's iconic Blohsh isotype.",
  "Llavero Metálico Coldplay": "Coldplay Metal Keychain",
  "Llavero metálico grabado con el logotipo de Coldplay \"Music of the Spheres\".": "Metal keychain engraved with the Coldplay \"Music of the Spheres\" logo.",
  "Sudadera Duki Diabla Negra": "Duki Black Diabla Hoodie",
  "Sudadera premium color negro con logo bordado en color rojo de la diabla.": "Premium black hoodie with red embroidered diabla logo.",
  "Poster Edición Limitada Steve Aoki": "Steve Aoki Limited Edition Poster",
  "Poster con acabado metálico firmado digitalmente por Steve Aoki. Edición numerada.": "Poster with metallic finish digitally signed by Steve Aoki. Numbered edition.",
  "Vaso Coleccionable Gamer Con 2026": "Gamer Con 2026 Collectible Cup",
  "Vaso de plástico rígido holográfico coleccionable de la convención de videojuegos.": "Collectible rigid holographic plastic cup from the video game convention.",
  "Playera Karol G Bichota Blanca": "Karol G White Bichota T-Shirt",
  "Playera blanca con diseño floral e impresión frontal del single \"Bichota\" de Karol G.": "White t-shirt with floral design and front printing of Karol G's single \"Bichota\".",
  "Sudadera The Weeknd XO Logo": "The Weeknd XO Logo Hoodie",
  "Sudadera ultra suave con estampado del logo XO de The Weeknd en el pecho.": "Ultra soft hoodie with The Weeknd XO logo print on the chest.",
  "Calcomanías Pack Rock & Metal": "Rock & Metal Stickers Pack",
  "Paquete con 12 calcomanías impermeables de vinilo con logos de bandas de rock y metal.": "Pack of 12 waterproof vinyl stickers with rock and metal band logos.",
  "Gorro de Lana Red Hot Chili Peppers": "Red Hot Chili Peppers Wool Beanie",
  "Gorro de lana tejido con el clásico isotipo del asterisco de los Red Hot Chili Peppers.": "Wool beanie knitted with the classic Red Hot Chili Peppers asterisk isotype.",
  "Mochila Impermeable Tomorrowland": "Tomorrowland Waterproof Backpack",
  "Mochila ligera e impermeable con el logotipo de Tomorrowland, perfecta para festivales.": "Lightweight and waterproof backpack with the Tomorrowland logo, perfect for festivals.",
  "Playera Travis Scott Utopia": "Travis Scott Utopia T-Shirt",
  "Playera de corte holgado con tipografía exclusiva del disco Utopia de Travis Scott.": "Loose fit t-shirt with exclusive Travis Scott's Utopia album typography.",
  "Sudadera Eminem Shady Records": "Eminem Shady Records Hoodie",
  "Sudadera conmemorativa color gris jaspeado con el logo clásico de Shady Records.": "Commemorative heather gray hoodie with the classic Shady Records logo.",
  "Playera Shakira Loba Edición": "Shakira Loba Edition T-Shirt",
  "Playera de colección de Shakira alusiva al icónico videoclip de \"She Wolf\".": "Shakira collector's t-shirt referring to the iconic \"She Wolf\" music video.",
  "Gorra Peso Pluma Double P": "Peso Pluma Double P Cap",
  "Gorra oficial tipo trucker con el bordado de las letras PP de Peso Pluma.": "Official trucker cap with Peso Pluma's PP letters embroidery.",
  "Llavero Acrílico Bizarrap Session": "Bizarrap Session Acrylic Keychain",
  "Llavero de acrílico de alta calidad con el logo oficial del productor Bizarrap.": "High-quality acrylic keychain with Bizarrap's official producer logo.",
  "Playera Justin Bieber Justice Tour": "Justin Bieber Justice Tour T-Shirt",
  "Playera de color verde neón oficial de la gira mundial Justice de Justin Bieber.": "Official neon green t-shirt from Justin Bieber's Justice world tour.",
  "Playera Steve Aoki Neon Logo": "Steve Aoki Neon Logo T-Shirt",
  "Playera negra con logo Aoki impreso en tinta reactiva a la luz negra o ultravioleta.": "Black t-shirt with Aoki logo printed in blacklight or UV reactive ink.",
  "Sudadera Coldplay Spheres Blanca": "Coldplay Spheres White Hoodie",
  "Sudadera blanca con el arte planetario del tour \"Music of the Spheres\" impreso a color.": "White hoodie with colorful printed \"Music of the Spheres\" tour planetary art.",
  "Gorra Bad Bunny Corazón": "Bad Bunny Heart Cap",
  "Gorra de mezclilla con el parche bordado del corazón triste de \"Un Verano Sin Ti\".": "Denim cap with the embroidered sad heart patch from \"Un Verano Sin Ti\".",
  "Termo Duki A.D.A Aluminio": "Duki A.D.A Aluminum Thermos",
  "Termo de aluminio para bebidas frías con la tipografía oficial del álbum A.D.A.": "Aluminum thermos for cold drinks with the official A.D.A. album typography.",
  "Case iPhone Laika Club Oficial": "Official Laika Club iPhone Case",
  "Funda protectora anticaídas compatible con iPhone con el logo neón de Laika Club.": "Shockproof protective case compatible with iPhone with the Laika Club neon logo.",
  "Playera Billie Eilish Oversized": "Billie Eilish Oversized T-Shirt",
  "Playera de corte holgado en color verde brillante característico de Billie Eilish.": "Loose fit t-shirt in bright green characteristic of Billie Eilish.",
  "Taza de Cerámica Rock Legends": "Rock Legends Ceramic Mug",
  "Taza de cerámica de 11oz apta para microondas con collage impreso de bandas legendarias.": "11oz microwave safe ceramic mug with printed collage of legendary bands.",
  "Calcomanías Pack Anime Fest VIP": "Anime Fest VIP Stickers Pack",
  "Colección de pegatinas de vinil de las series de anime y manga más populares del momento.": "Vinyl sticker collection of the most popular anime and manga series of the moment.",
  "Pulsera de Tela Tomorrowland Gold": "Tomorrowland Gold Fabric Wristband",
  "Pulsera de tela tejida de Tomorrowland con broche de seguridad de plástico. Conmemorativa.": "Tomorrowland woven fabric wristband with plastic safety clasp. Commemorative.",
  "Playera Bruno Mars 24K Magic": "Bruno Mars 24K Magic T-Shirt",
  "Playera estampada con letras doradas inspiradas en el exitoso álbum 24K Magic.": "Printed t-shirt with gold letters inspired by the hit 24K Magic album.",
  "Gorra Metallica Black Album": "Metallica Black Album Cap",
  "Gorra bordada de color negro con la icónica serpiente de la portada de Metallica.": "Black embroidered cap with the iconic serpent from Metallica's cover.",
  "Sudadera Karol G Bichota Rosa": "Karol G Pink Bichota Hoodie",
  "Sudadera color rosa pastel con tipografía e ilustraciones de flores de Karol G.": "Pastel pink hoodie with typography and flower illustrations by Karol G.",
  "Playera The Weeknd Starboy Tour": "The Weeknd Starboy Tour T-Shirt",
  "Playera retro que rememora el icónico álbum y gira Starboy de The Weeknd.": "Retro t-shirt that commemorates the iconic Starboy album and tour by The Weeknd.",
  "Termo Steve Aoki Dim Mak": "Steve Aoki Dim Mak Thermos",
  "Botella de vacío de acero inoxidable con el logo de la disquera Dim Mak de Aoki.": "Stainless steel vacuum bottle with Aoki's Dim Mak record label logo.",
  "Lanyard Duki SSJ Conmemorativa": "Duki SSJ Commemorative Lanyard",
  "Correa para llaves o credenciales alusiva al clásico \"Super Sangre Joven\" de Duki.": "Key or credential strap referring to the classic \"Super Sangre Joven\" by Duki.",
  "Llavero Funko Pop DJ Steve Aoki": "Funko Pop DJ Steve Aoki Keychain",
  "Llavero oficial coleccionable de vinilo en miniatura de la figura de Steve Aoki.": "Official collectible miniature vinyl keychain of the Steve Aoki figure.",
  "Playera Oficial Rock in Laika": "Official Rock in Laika T-Shirt",
  "Playera del festival de rock con todas las bandas participantes impresas en la espalda.": "Rock festival t-shirt with all participating bands printed on the back.",
  "Poster Holográfico Daft Punk": "Daft Punk Holographic Poster",
  "Poster impreso sobre papel holográfico con los cascos de Daft Punk brillando en 3D.": "Poster printed on holographic paper with Daft Punk helmets shining in 3D.",
  "Sudadera Travis Scott Astroworld": "Travis Scott Astroworld Hoodie",
  "Sudadera conmemorativa multicolor con el lema \"Wish You Were Here\" bordado.": "Multicolor commemorative hoodie with the slogan \"Wish You Were Here\" embroidered.",
  "Gorra Eminem Rap God bordada": "Eminem Rap God Embroidered Cap",
  "Gorra plana de hip hop color negro bordada en 3D con el texto Rap God.": "Flat hip hop black cap embroidered in 3D with the text Rap God.",
  "Vaso Térmico Shakira Pies Descalzos": "Shakira Pies Descalzos Thermal Cup",
  "Vaso térmico hermético de doble pared con design retro de la fundación Pies Descalzos.": "Airtight double-wall thermal cup with retro design from the Pies Descalzos foundation.",
  "Playera Peso Pluma Génesis": "Peso Pluma Genesis T-Shirt",
  "Playera oficial alusiva al exitoso álbum Génesis de Peso Pluma. Ajuste holgado.": "Official t-shirt referencing Peso Pluma's successful Genesis album. Loose fit.",
  "Sudadera Bizarrap Session Oficial": "Official Bizarrap Session Hoodie",
  "Sudadera premium unisex con capucha inspirada en las sesiones de Bizarrap.": "Premium unisex hoodie with hood inspired by Bizarrap sessions.",
  "Termo Justin Bieber Peaches": "Justin Bieber Peaches Thermos",
  "Termo color melocotón de acero inoxidable con el single Peaches impreso.": "Peach-colored stainless steel thermos with the printed single Peaches.",
  "Set de Pines Retro Laika Club": "Laika Club Retro Pins Set",
  "Juego de 5 pines metálicos esmaltados con diferentes logotipos vintage de Laika.": "Set of 5 enameled metal pins with different vintage Laika logos.",

  // --- OPERATOR PORTAL (ADDITIONAL) ---
  "Por favor, ingrese el código del boleto.": "Please enter the ticket code.",
  "Descripción Requerida": "Description Required",
  "Por favor, proporcione los detalles del incidente.": "Please provide the details of the incident.",
  "Incidencia Guardada": "Incident Saved",
  "El reporte se ha enviado con éxito al servidor central.": "The report has been successfully sent to the central server.",
  "No se pudo guardar el incidente.": "Could not save the incident.",
  "Registrando incidencia...": "Registering incident...",
  "Incidencias": "Incidents",
  "Reporte de anomalías e infracciones en el acceso.": "Report of anomalies and access violations.",
  "Nuevo Reporte de Puerta": "New Gate Report",
  "Código de Boleto": "Ticket Code",
  "Categoría de Incidencia": "Incident Category",
  "Descripción Detallada": "Detailed Description",
  "Detalla lo sucedido (ej. Persona intentó ingresar con copia impresa de código ya escaneado, titular presentaba credenciales apócrifas...)": "Detail what happened (e.g. Person tried to enter with a printed copy of an already scanned code, holder presented fake credentials...)",
  "Enviar Reporte": "Send Report",
  "Reportes Recientes del Turno": "Recent Shift Reports",
  "No hay incidencias reportadas en este turno.": "There are no reported incidents in this shift.",
  "Boleto Duplicado": "Duplicate Ticket",
  "Código QR Dañado": "Damaged QR Code",
  "Suplantación de Identidad": "Impersonation",
  "Altercado en Acceso": "Access Altercation",
  "Otro Incidente": "Other Incident",
  "Incidente": "Incident",
  "Obteniendo estadísticas...": "Getting statistics...",
  "Bitácora y Estadísticas": "Log & Statistics",
  "Resumen analítico de validaciones durante el día.": "Analytical summary of validations during the day.",
  "Total Escaneados": "Total Scanned",
  "Accesos Exitosos": "Successful Accesses",
  "Boletos Rechazados": "Rejected Tickets",
  "Tasa de Aprobación": "Approval Rate",
  "de": "of",
  "boletos presentados resultaron auténticos.": "tickets presented were authentic.",
  "Historial de Lecturas Recientes": "Recent Readings History",
  "No hay lecturas registradas en la bitácora.": "There are no readings registered in the log.",
  "Inválido": "Invalid",
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>('es');

  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const stored = await AsyncStorage.getItem('@laika_language_preference');
        if (stored === 'en' || stored === 'es') {
          setLanguageState(stored);
        }
      } catch (e) {
        console.error('Error loading language preference:', e);
      }
    };
    loadLanguage();
  }, []);

  const setLanguage = async (lang: LanguageCode) => {
    try {
      setLanguageState(lang);
      await AsyncStorage.setItem('@laika_language_preference', lang);
    } catch (e) {
      console.error('Error saving language preference:', e);
    }
  };

  const t = (key: string): string => {
    if (!key) return '';
    if (language === 'es') {
      return key; // Spanish is the default language keys
    }

    // Clean key of leading/trailing space for more robust lookup
    const trimmedKey = key.trim();
    if (enTranslations[trimmedKey] !== undefined) {
      return enTranslations[trimmedKey];
    }

    // Try substring matching for specific templates like "Visa •••• 1234"
    if (trimmedKey.startsWith("Visa ••••")) {
      return trimmedKey.replace("Visa ••••", "Visa ••••");
    }

    // Try status matching if it's uppercase
    if (trimmedKey === "VIGENTE") return "ACTIVE";
    if (trimmedKey === "CANJEADO") return "REDEEMED";
    if (trimmedKey === "REEMBOLSADO") return "REFUNDED";

    return key; // Fallback to Spanish key if no translation exists
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
